In [1]:
import pandas as pd

In [4]:
df = pd.read_excel('C:/Users/wnrrh/desktop/data/통행량/통행량 raw.xlsx',header=0)
tra = pd.read_excel('C:/Users/wnrrh/desktop/data/통행량/traffic_final.xlsx',header=0)

In [8]:
columns= ['지점명','통행량','시간대구분','도로명']
tra.columns = columns

In [10]:
columns = ['지점번호','지점명','위도','경도','주소','도로명 주소','유입 방향','유출방향']
df.columns = columns

In [11]:
df.drop(['지점번호','도로명 주소','유입 방향','유출방향'],axis=1,inplace=True)
df

             지점명         위도          경도                    주소
0      성산로(금화터널)  37.568588  126.948436    서울시 서대문구 신촌동 1-142
1      사직로(사직터널)  37.572298  126.962853     서울시 종로구 행촌동 1-186
2    자하문로(자하문터널)  37.588831  126.968548      서울시 종로구 청운동 24-6
3     대사관로(삼청터널)  37.596359  126.984209   서울시 성북구 성북동 산25-148
4       율곡로(안국역)  37.576000  126.984342      서울시 종로구 경운동 90-4
..           ...        ...         ...                   ...
130       동부간선도로  37.568685  127.076023     서울시 동대문구 장안동 19-7
131       경부고속도로  37.493135  127.022533  서울시 서초구 서초동 1748-26
132        분당수서로  37.497648  127.087195     서울시 강남구 일원동 467-1
133  강남순환로(관악터널)  37.449096  126.926169    서울시 금천구 시흥동 산 93-1
134       서부간선도로  37.520965  126.881826     서울시 영등포구 문래동6가 52

[135 rows x 4 columns]

In [12]:
traffic = pd.merge(df,tra, on=['지점명'],how = 'right')
traffic

,지점명,위도,경도,주소,통행량,시간대구분,도로명
0,가양대교,37.571567,126.862726,서울시 마포구 상암동 506-68,809.849267,0,화곡로
1,가양대교,37.571567,126.862726,서울시 마포구 상암동 506-68,546.695207,1,화곡로
2,가양대교,37.571567,126.862726,서울시 마포구 상암동 506-68,391.760086,2,화곡로
3,가양대교,37.571567,126.862726,서울시 마포구 상암동 506-68,320.259190,3,화곡로
4,가양대교,37.571567,126.862726,서울시 마포구 상암동 506-68,353.127919,4,화곡로
...,...,...,...,...,...,...,...
6835,화랑로(화랑대역),37.619936,127.082950,"서울시, 노원구 공릉동 280-2",1797.089406,19,화랑로
6836,화랑로(화랑대역),37.619936,127.082950,"서울시, 노원구 공릉동 280-2",1764.157896,20,화랑로
6837,화랑로(화랑대역),37.619936,127.082950,"서울시, 노원구 공릉동 280-2",1769.696755,21,화랑로
6838,화랑로(화랑대역),37.619936,127.082950,"서울시, 노원구 공릉동 280-2",1634.732259,22,화랑로
6839,화랑로(화랑대역),37.619936,127.082950,"서울시, 노원구 공릉동 280-2",1436.498055,23,화랑로

In [13]:
traffic.to_excel('C:/Users/wnrrh/desktop/data/traffic_start.xlsx')