In [45]:
import pandas as pd
import numpy as np

In [46]:
df = pd.read_excel('C:/Users/wnrrh/desktop/data/현황/광진도봉.xlsx',header = 0)

In [47]:
columns = ['대상시설명','소재지도로명주소','자치구','시설종류','구역지정수',
          'CCTV설치여부','CCTV 수','시설물 도로표지판 수','시설물 과속방지턱 수',
           '보호구역도로폭','위도','경도']
df.columns = columns

In [48]:
df.drop(['자치구'],axis=1, inplace = True)

In [49]:
df = df.rename(columns={'소재지도로명주소':'주소'})
df

,대상시설명,주소,시설종류,구역지정수,CCTV설치여부,CCTV 수,시설물 도로표지판 수,시설물 과속방지턱 수,보호구역도로폭,위도,경도
0,경일어린이집,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
1,연촌초등학교,서울특별시 노원구 공릉로58길 36 (하계동),초등학교,3,Y,4,7~15,10,4,37.634416,127.072512
2,신창어린이집,서울특별시 도봉구 덕릉로62길 26 (창동),어린이집,1,Y,0,8,0,0,37.640093,127.041305
3,창4동어린이집,서울특별시 도봉구 마들로 339-13 (창동),어린이집,1,Y,0,8,0,4,37.642164,127.053289
4,꿈동산몬테소리어린이집,서울특별시 광진구 면목로4길 3 (군자동),어린이집,2,Y,0,NaN,0,0,37.555820,127.076065
...,...,...,...,...,...,...,...,...,...,...,...
323,코레일오류동어린이집,서울특별시 구로구 경인로20가길 24 (오류동),어린이집,2,Y,0,NaN,0,0,37.495483,126.845330
324,항동어린이집,서울특별시 구로구 연동로 284 (항동),어린이집,1,Y,0,NaN,0,4,37.485379,126.823438
325,개봉초등학교 병설유치원,서울특별시 구로구 개봉로16길 30-11 (개봉동),유치원(병설),0,Y,0,NaN,0,0,37.489523,126.857975
326,서울고척초등학교 병설유치원,서울특별시 구로구 경서로 31 (고척동),유치원(병설),0,Y,0,NaN,0,0,37.500947,126.856994
327,꿀벌유치원,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317

In [51]:
time = pd.DataFrame([], columns = ['시간대'] + list(df.keys())[:11] + list(df.keys())[13:])
for i in range(len(df)):
    for t in range(1,25):
        time.loc[len(time)] = ([t] + list(df.iloc[i,:11]) + list(df.iloc[i,13:]))
time = time.iloc[:,[1,0]+[i for i in range(2, len(time.keys()))]]
time

,대상시설명,시간대,주소,시설종류,구역지정수,CCTV설치여부,CCTV 수,시설물 도로표지판 수,시설물 과속방지턱 수,보호구역도로폭,위도,경도
0,경일어린이집,1,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
1,경일어린이집,2,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
2,경일어린이집,3,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
3,경일어린이집,4,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
4,경일어린이집,5,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
...,...,...,...,...,...,...,...,...,...,...,...,...
7867,꿀벌유치원,20,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7868,꿀벌유치원,21,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7869,꿀벌유치원,22,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7870,꿀벌유치원,23,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7871,꿀벌유치원,24,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317

In [52]:
df = time
df['시간대'] = df['시간대'].apply(lambda x: "{:0>2d}".format(x))

df

,대상시설명,시간대,주소,시설종류,구역지정수,CCTV설치여부,CCTV 수,시설물 도로표지판 수,시설물 과속방지턱 수,보호구역도로폭,위도,경도
0,경일어린이집,01,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
1,경일어린이집,02,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
2,경일어린이집,03,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
3,경일어린이집,04,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
4,경일어린이집,05,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
...,...,...,...,...,...,...,...,...,...,...,...,...
7867,꿀벌유치원,20,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7868,꿀벌유치원,21,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7869,꿀벌유치원,22,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7870,꿀벌유치원,23,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7871,꿀벌유치원,24,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317

In [53]:
df['시간대'] = df['시간대'].map('{}시'.format)

In [54]:
df

,대상시설명,시간대,주소,시설종류,구역지정수,CCTV설치여부,CCTV 수,시설물 도로표지판 수,시설물 과속방지턱 수,보호구역도로폭,위도,경도
0,경일어린이집,01시,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
1,경일어린이집,02시,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
2,경일어린이집,03시,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
3,경일어린이집,04시,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
4,경일어린이집,05시,서울특별시 도봉구 도당로13길 34-5 (방학동),어린이집,1,Y,0,6,0,2,37.666418,127.034903
...,...,...,...,...,...,...,...,...,...,...,...,...
7867,꿀벌유치원,20시,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7868,꿀벌유치원,21시,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7869,꿀벌유치원,22시,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7870,꿀벌유치원,23시,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317
7871,꿀벌유치원,24시,서울특별시 구로구 디지털로27다길 15 (구로동),유치원(일반),3,Y,0,NaN,0,0,37.484935,126.889317

In [55]:
df.to_excel("C:/Users/wnrrh/desktop/data/현황/광진도봉 마무리.xlsx")

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7872 entries, 0 to 7871
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   대상시설명        7872 non-null   object
 1   시간대          7872 non-null   object
 2   주소           7872 non-null   object
 3   시설종류         7872 non-null   object
 4   구역지정수        7872 non-null   object
 5   CCTV설치여부     7872 non-null   object
 6   CCTV 수       7872 non-null   object
 7   시설물 도로표지판 수  4632 non-null   object
 8   시설물 과속방지턱 수  7872 non-null   object
 9   보호구역도로폭      7872 non-null   object
 10  위도           7848 non-null   float64
 11  경도           7848 non-null   float64
dtypes: float64(2), object(10)
memory usage: 799.5+ KB