In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('C:/Users/wnrrh/desktop/data/전처리/생활인구수제외 보호구역 현황.xlsx',header=0)

In [3]:
data_list = df['주소'].str.split()
df['자치구'] = data_list.str.get(1)
df

,시설명,시간대,주소,시설종류,구역지정수,CCTV 수,도로표지판 수,과속방지턱 수,위도,경도,CCTV설치여부,보호구역도로폭,도로명,속도,자치구
0,도원유치원,01시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.50,새창로,24.000878,용산구
1,새현대유치원,01시,"서울특별시 마포구 새창로 52 (도화동, 도화동현대아파트)",유치원(일반),3,0,0.0,5,37.540387,126.953599,Y,12.35,새창로,24.000878,마포구
2,도원유치원,02시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.50,새창로,25.932575,용산구
3,새현대유치원,02시,"서울특별시 마포구 새창로 52 (도화동, 도화동현대아파트)",유치원(일반),3,0,0.0,5,37.540387,126.953599,Y,12.35,새창로,25.932575,마포구
4,도원유치원,03시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.50,새창로,27.128114,용산구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36235,구립서초남서울어린이집,20시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,23.216505,서초구
36236,구립서초남서울어린이집,21시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,27.570112,서초구
36237,구립서초남서울어린이집,22시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,29.632731,서초구
36238,구립서초남서울어린이집,23시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,31.041454,서초구
36239,구립서초남서울어린이집,24시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,34.509565,서초구

In [4]:
student = pd.read_excel('C:/Users/wnrrh/desktop/data/전처리/학생 수.xlsx',header=0)
columns = ['자치구','기관명','주소','학생 수']
student.columns = columns
student

      자치구           기관명                    주소  학생 수
0     송파구     수협아라맘어린이집      서울특별시 송파구 오금로 62    10
1     구로구        비룡어린이집   서울특별시 구로구 고척로33길 43    63
2     강남구  현대백화점 직장어린이집  서울특별시 강남구 테헤란로98길 12     5
3     강남구  크래프톤 역삼 어린이집   서울특별시 강남구 논현로99길 21     6
4     금천구        예솔어린이집     서울특별시 금천구 벚꽃로 100    17
...   ...           ...                   ...   ...
6498  은평구        은평대영학교   서울특별시 은평구 갈현로11길 30    76
6499  강동구          주몽학교     서울특별시 강동구 상암로 369    69
6500  강동구        한국구화학교  서울특별시 강동구 고덕로 295-59    62
6501  송파구        한국육영학교    서울특별시 송파구 충민로6길 15    80
6502  강북구         한빛맹학교  서울특별시 강북구 삼양로73가길 47    37

[6503 rows x 4 columns]

In [5]:
student = student.rename(columns={'기관명':'시설명'})

In [6]:
student = student.drop(['주소'],axis=1, inplace= False)
student

      자치구           시설명  학생 수
0     송파구     수협아라맘어린이집    10
1     구로구        비룡어린이집    63
2     강남구  현대백화점 직장어린이집     5
3     강남구  크래프톤 역삼 어린이집     6
4     금천구        예솔어린이집    17
...   ...           ...   ...
6498  은평구        은평대영학교    76
6499  강동구          주몽학교    69
6500  강동구        한국구화학교    62
6501  송파구        한국육영학교    80
6502  강북구         한빛맹학교    37

[6503 rows x 3 columns]

In [7]:
dataframe = pd.merge(df,student, on=['시설명','자치구'], how = 'inner')
dataframe

,시설명,시간대,주소,시설종류,구역지정수,CCTV 수,도로표지판 수,과속방지턱 수,위도,경도,CCTV설치여부,보호구역도로폭,도로명,속도,자치구,학생 수
0,도원유치원,01시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.5,새창로,24.000878,용산구,82
1,도원유치원,02시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.5,새창로,25.932575,용산구,82
2,도원유치원,03시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.5,새창로,27.128114,용산구,82
3,도원유치원,04시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.5,새창로,28.053681,용산구,82
4,도원유치원,05시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.5,새창로,27.848151,용산구,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22579,서울반원초등학교,20시,서울특별시 서초구 잠원로3길 28 (잠원동),초등학교,1,0,0.0,8,37.508212,127.003632,Y,4.0,잠원로,24.388534,서초구,1373
22580,서울반원초등학교,21시,서울특별시 서초구 잠원로3길 28 (잠원동),초등학교,1,0,0.0,8,37.508212,127.003632,Y,4.0,잠원로,25.992141,서초구,1373
22581,서울반원초등학교,22시,서울특별시 서초구 잠원로3길 28 (잠원동),초등학교,1,0,0.0,8,37.508212,127.003632,Y,4.0,잠원로,26.579250,서초구,1373
22582,서울반원초등학교,23시,서울특별시 서초구 잠원로3길 28 (잠원동),초등학교,1,0,0.0,8,37.508212,127.003632,Y,4.0,잠원로,27.120034,서초구,1373
22583,서울반원초등학교,24시,서울특별시 서초구 잠원로3길 28 (잠원동),초등학교,1,0,0.0,8,37.508212,127.003632,Y,4.0,잠원로,29.189781,서초구,1373

In [8]:
data = pd.read_excel('C:/Users/wnrrh/desktop/data/전처리/생활인구수제외 보호구역 현황.xlsx',header=0)
data

,시설명,시간대,주소,시설종류,구역지정수,CCTV 수,도로표지판 수,과속방지턱 수,위도,경도,CCTV설치여부,보호구역도로폭,도로명,속도
0,도원유치원,01시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.50,새창로,24.000878
1,새현대유치원,01시,"서울특별시 마포구 새창로 52 (도화동, 도화동현대아파트)",유치원(일반),3,0,0.0,5,37.540387,126.953599,Y,12.35,새창로,24.000878
2,도원유치원,02시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.50,새창로,25.932575
3,새현대유치원,02시,"서울특별시 마포구 새창로 52 (도화동, 도화동현대아파트)",유치원(일반),3,0,0.0,5,37.540387,126.953599,Y,12.35,새창로,25.932575
4,도원유치원,03시,서울특별시 용산구 새창로12길 11-8,유치원,2,0,0.0,3,37.538778,126.957624,Y,6.50,새창로,27.128114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36235,구립서초남서울어린이집,20시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,23.216505
36236,구립서초남서울어린이집,21시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,27.570112
36237,구립서초남서울어린이집,22시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,29.632731
36238,구립서초남서울어린이집,23시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,31.041454
36239,구립서초남서울어린이집,24시,서울특별시 서초구 반포대로 310-5 (잠원동),어린이집,1,0,0.0,1,37.506831,127.000883,N,1.00,반포대로,34.509565

In [10]:
data.isnull().sum()

시설명          0
시간대          0
주소           0
시설종류         0
구역지정수        0
CCTV 수       0
도로표지판 수      0
과속방지턱 수      0
위도          48
경도          72
CCTV설치여부     0
보호구역도로폭      0
도로명          0
속도           0
dtype: int64

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36240 entries, 0 to 36239
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   시설명       36240 non-null  object
 1   시간대       36240 non-null  object
 2   주소        36240 non-null  object
 3   시설종류      36240 non-null  object
 4   구역지정수     36240 non-null  int64
 5   CCTV 수    36240 non-null  int64
 6   도로표지판 수   36240 non-null  float64
 7   과속방지턱 수   36240 non-null  int64
 8   위도        36192 non-null  float64
 9   경도        36168 non-null  float64
 10  CCTV설치여부  36240 non-null  object
 11  보호구역도로폭   36240 non-null  float64
 12  도로명       36240 non-null  object
 13  속도        36240 non-null  float64
dtypes: float64(5), int64(3), object(6)
memory usage: 3.9+ MB